name: Run_Plat_Price

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PLAT_PRICE_KEY: ${{ secrets.PLAT_PRICE_KEY }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9.17
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.17

    - name: Install Poetry
      run: |
        pwd
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies
      run: |
        ls
        poetry config virtualenvs.create false
        poetry install
    - name: Run Python Script
      run: python scrape_plat_prices.py
